### ISSUE TITLE
Installtion failed

### ISSUE THREAD

**Issue by anmol26s** [scith/docker_odoo_ynh#1]
I am getting installation failed while installing 

https://datamol.in/zerobin/?6cc08a4f92cf5ab3#Cb6ESNwlClFU5v+b1yjZ7gNPtpWa1w3mU8V8nqCZoQc=

**Comment by scith** [comment]
Hi, which Debian are you using?
In terminal, could you try "sudo docker ps" ?

**Comment by anmol26s** [comment]
Hi
I am using Debian Jessie.
Here is the result of the commands.
https://datamol.in/zerobin/?8346a4f35486f52b#LXWXKht/XgBr6F1CkQ2Gi6VcNhjN3SrcZcn/GyRXuCo=

**Comment by scith** [comment]
Thanks,
Can you type in terminal:
sudo docker run -d -e POSTGRES_USER=odoo -e POSTGRES_PASSWORD=odoo --name odoodb postgres

(if it is already created, type "sudo docker stop odoodb" and "sudo docker rm odoodb"
It looks like the script cannot run the container

**Comment by anmol26s** [comment]
Here is the output

https://datamol.in/zerobin/?d8f93b5f3897f795#Ri78MixR00LOIo147BoTe/oVyUbQGVQ6IRitFfiy8m4=

**Comment by scith** [comment]
Thanks, we're getting close...
Could you please type:
sudo systemctl enable docker
sudo systemctl restart docker
sudo docker stop odoodb
sudo docker rm odoodb

and try reinstall? thanks

**Comment by anmol26s** [comment]
Here is the output
https://datamol.in/zerobin/?19540d54095ef8d7#FE8gRVz9VOhBMUggJiYSyTPAVIfLsyAB/LNBvx/Wh8Y=

**Comment by scith** [comment]
and:
sudo yunohost service start docker
sudo docker stop odoodb
sudo docker rm odoodb

?

**Comment by anmol26s** [comment]
yes I am on Debian 8 Jessie. I have no idea why systemctl is not installed.
Still no success in installing odoodb.
Here is the output.
https://datamol.in/zerobin/?19c367c1ffcb619b#dpEH2FqVPzy/FM7juSoMmIDTDVgfz2U+72Zv1qXuD/8=

**Comment by scith** [comment]
Thanks,
I tried to submit a fix. Could you try reinstalling please?

**Comment by anmol26s** [comment]
It still fails
https://datamol.in/zerobin/?25349d096df5790e#lHItF7sedrprFgRVqAHGu6odewSXK/YAyuvpo+bH7QQ=

**Comment by scith** [comment]
We're almost there!
Please run:
sudo yunohost service stop docker
sudo yunohost service start docker
sudo docker stop odoo
sudo docker stop odoodb
sudo docker rm odoo
sudo docker rm odoodb

(to remove the old containers)
Then try reinstalling :)

**Comment by anmol26s** [comment]
ohhuu...at last success.
Thank you 
Please do tell if I want to remove it and install it on new domain like company.datamol.in
How to do it ?

**Comment by scith** [comment]
Cool! Thanks for sharing this bug, I'll fix in my other repositories as well :)
You can remove the app with:
sudo yunohost app remove dockerodoo

and then reinstall as normal
