### ISSUE TITLE
after uninstallation odoo not reinstalling 

### ISSUE THREAD

**Issue by anmol26s** [scith/docker_odoo_ynh#2]
Hi

I can not reinstall after uninstall .
https://datamol.in/zerobin/?e98ccc708bfc4c0d#QQqWvDhiyVnvMXT+auvWBpY9aA85m4gEm5jYwL+RRPM=

**Comment by scith** [comment]
Hi, check that the container has been stopped:
sudo docker ps
should not show odoo or odoodb. If it does:
sudo docker stop odoo
sudo docker rm odoo
sudo docker stop odoodb
sudo docker rm odoodb

If it still does not work, try:
sudo yunohost firewall disallow TCP 8069

**Comment by anmol26s** [comment]
It is still not installing 

https://datamol.in/zerobin/?c57595296b5f08e8#ttgY/+3uyxEZp8cJb5NpWE6Rb7bNFb3gk8++sGlNcOE=

**Comment by scith** [comment]
And
sudo service docker status
sudo service docker stop
sudo service docker start
?

It is still the same problem than before, weird :(

**Comment by anmol26s** [comment]
yunohost] root ~ #   sudo service docker status
[ ok ] Docker is running.
[yunohost] root ~ #   sudo service docker stop
[ ok ] Stopping Docker: docker.
[yunohost] root ~ #   sudo service docker start
[ ok ] Starting Docker: docker.
[yunohost] root ~ #

**Comment by scith** [comment]
Hi, could you do;
sudo service docker restart
sudo docker ps
?

**Comment by anmol26s** [comment]
Hi
I have solved the issue by 
sudo yunohost service stop docker
sudo yunohost service start docker
sudo docker stop odoo
sudo docker stop odoodb
sudo docker rm odoo
sudo docker rm odoodb

and then reinstalling odoo container
Thanks 
you can close the issue .
