### ISSUE TITLE
Impossible de restaurer une base de données

### ISSUE THREAD

**Issue by bobo-romania** [scith/docker_odoo_ynh#6]
Il est impossible de restaurer une base de données existante via l'interface de gestion des bases de données 
DOMAINE.ORG/web/database/

Deux messages contradictoires apparaissent
![Uploading bug_restauration_bdd_odoo.png…]()

le fichier de log sur le container odoo est vide.
``` docker exec -ti odoo /bin/bash```
J'ai regardé dans ce dossier de log, 

``` /var/log/odoo ```

Je n'ai pas de piste pour expliciter ce problème

**Comment by scith** [comment]
Salut, le problème vient de nginx et je ne sais pas comment le régler :(
Le seul moyen que j'ai trouvé est d'ouvrir le port 8069 et d'y accéder depuis l'IP du serveur:8069.
J'ai le même soucis avec quelques autres pages qui donnent des timeouts avec la redirection, mais pas avec l'accès direct depuis le port ...

**Comment by scith** [comment]
Si ouvrir le port ne marche pas, tu peux détruire le conteneur odoo (possible que ça supprime les données avec mais pas sûr ... Peut-être que tout est dans la BDD dans ce cas pas de données perdues, mais à tes risques et périls !)

Et en recréer un avec la commande :
sudo docker run -d --restart always -p 8069:8069 --name odoo --link odoodb:db -t odoo

(donc sans le -p 127.0.0.1:8069:8069, comme ça le port 8069 est accessible depuis IPduserveur:8069)

**Comment by scith** [comment]
Salut, le problème vient de nginx et je ne sais pas comment le régler :(
Le seul moyen que j'ai trouvé est d'y accéder depuis l'IP du serveur:8069.
J'ai le même soucis avec quelques autres pages qui donnent des timeouts avec la redirection, mais pas avec l'accès direct depuis le port ...

Du coup j'ai fait un mini changement dans le code d'install pour qu'on puisse accéder à Odoo depuis http://IP_du_serveur:8069

Si tu veux faire la manip en "essayant" de conserver tes donnéees (pas sur que les données restent, à tester ...)
sudo docker stop odoo
sudo docker rm odoo
sudo docker run -d --restart always -p 8069:8069 --name odoo --link odoodb:db -t odoo

**Comment by scith** [comment]
Ah et au fait j'avais déjà reporté ces issues dans 2 autres items :smile: 
Je rajouterai des choses dans issues si j'en trouve d'autres

**Comment by bobo-romania** [comment]
Salut, de mon côté, cela fonctionne en faisant cette petite technique de sioux. 
merci de ton retour.
Je vais essayer de transmettre le noeud sur lequel tu es pour  nginx.
et sinon ... correct, je viens de voir les autres issues. hum ...

**Comment by scith** [comment]
Salut, je pense être parvenu à résoudre le soucis en rajoutant une ligne dans le fichier nginx.
Du coup j'ai refermé à nouveau le port 8069 dans le conteneur pour éviter l'accès direct.
Tu me diras si ça marche (désolé pour le côté bidouille de mon application ... Elle est très experimentale pour le moment)
