### ISSUE TITLE
Issue with IPTABLES when trying to re-install the app

### ISSUE THREAD

**Issue by bobo-romania** [scith/docker_odoo_ynh#7]
Hi, 
I decided to reinstall the app and I got an error when I write
``` yunohost app install https://github.com/scith/docker_odoo_ynh.git ```
I get this message:
```Error response from daemon: Cannot start container 5c526151cf52d4953e9f612a6bb584bcce7cd2ab9b560a43148b518c1608ae7b: iptables failed: iptables --wait -t filter -A DOCKER ! -i docker0 -o docker0 -p tcp -d 172.17.0.14 --dport 8069 -j ACCEPT: iptables: No chain/target/match by that name.```
I don't really understand how Iptables works. here is some leads:
https://serverfault.com/questions/608870/error-iptables-no-chain-target-match-by-that-name
https://www.linuxquestions.org/questions/linux-security-4/iptables-iptables-no-chain-target-match-by-that-name-941406/

EDIT:
After a reboot, the installation process stop at the checkport stage.
```+ sudo yunohost app checkport 8069
Erreur : Le port 8069 n'est pas disponible
Erreur : Échec de l'installation```

I tried to open it throw the web inteface but it doesn't changed anything. Here is the opened ports
```
yunohost firewall list:
opened_ports: 
  - 22
  - 25
  - 53
  - 80
  - 443
  - 465
  - 587
  - 993
  - 5222
  - 5269
  - 5353
  - 8069
  - 9000```

**Comment by scith** [comment]
Hi, I think you have to close it instead for the app to be installed.
sudo yunohost firewall disallow TCP 8069
(I think this is the command, but it might not be... You could try yunohost firewal --h)

**Comment by scith** [comment]
Do you still have this issue?
Can you try doing "sudo yunohost service stop docker" before installing?

**Comment by scith** [comment]
You should check my new app https://github.com/scith/odoo_ynh
YunoHost users can log into the app directly!
